// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_BongDa.Data;

#nullable disable

namespace Web_BongDa.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260124015533_ChangeLogoPaths")]
    partial class ChangeLogoPaths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_BongDa.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Drawn")
                        .HasColumnType("int");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Lost")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Played")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("RedCards")
                        .HasColumnType("int");

                    b.Property<int>("Won")
                        .HasColumnType("int");

                    b.Property<int>("YellowCards")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Drawn = 1,
                            Logo = "/image/Mc.jpg",
                            Lost = 1,
                            Name = "Manchester City",
                            Played = 10,
                            Points = 25,
                            RedCards = 0,
                            Won = 8,
                            YellowCards = 5
                        },
                        new
                        {
                            Id = 2,
                            Drawn = 2,
                            Logo = "/Image/Ars.jpg",
                            Lost = 1,
                            Name = "Arsenal",
                            Played = 10,
                            Points = 23,
                            RedCards = 1,
                            Won = 7,
                            YellowCards = 12
                        },
                        new
                        {
                            Id = 3,
                            Drawn = 3,
                            Logo = "/image/Liver.png",
                            Lost = 1,
                            Name = "Liverpool",
                            Played = 10,
                            Points = 21,
                            RedCards = 0,
                            Won = 6,
                            YellowCards = 8
                        },
                        new
                        {
                            Id = 4,
                            Drawn = 3,
                            Logo = "/Image/Mu.jpg",
                            Lost = 3,
                            Name = "Manchester United",
                            Played = 10,
                            Points = 15,
                            RedCards = 2,
                            Won = 4,
                            YellowCards = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
